site_name: Celeste's Girl
site_url: https://art.tightbytes.com
edit_uri: "http://127.0.0.1:8000/docs/"
use_directory_urls: true
theme:
  name: material
  logo: assets/images/logo.png
  variant: classic

  favicon: assets/images/favicon.png

  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode

    # Dark mode
    - scheme: slate
      primary: indigo
      accent: white
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/custom.css
  - stylesheets/extras.css

nav:
  - Home: index.md

  - Charlotte:
      - Charlotte/index.md
      - Celeste's Girl v1: Charlotte/CG-1Scenes.md
      - Celeste's Girl v2: Charlotte/CG-2Scenes.md
      - Holding The Knife: Charlotte/C3-HTheKnife.md
      - Aa- Structure: Charlotte/Aa-Structure.md
      - Ab-- Emotions: Charlotte/Ab-Emotions.md
      - Canon Bible 1: Charlotte/CanonBible.md

  - Claudia:
      - Claudia/index.md
      - Canon Bible1: Claudia/CanonBible.md
      - NoteTemplate: Claudia/Notes26-00-00.md
      - Notes-260321: Claudia/Notes26-03-21a.md

  - Emily:
      - Emily/index.md
      - Metaphor Writing: Emily/MetaphorWriting.md
      - Notes Feb 23: Emily/Notes26-02-23.md
      - Notes Feb 28: Emily/Notes26-02-28.md
      - Notes Mar 03: Emily/Notes26-03-03.md
      - Notes Mar 04: Emily/Notes26-03-04.md
      - Notes Mar 06: Emily/Notes26-03-06.md
      - Notes Mar 08: Emily/Notes26-03-08.md
      - Notes Apr 02: Emily/Notes26-04-02.md
      - NoteTemplate: Emily/Notes26-00-00.md

  - Dev:
      - Dev/index.md
      - ArtiI Illustrious: Dev/ai-Illust.md
      - AI Imaging Models: Dev/aiModels.md
      - Banners and Stuff: Dev/Banners.md
      - Careful Ideas Now: Dev/Careful.md
      - ComfyUI Guidance: Dev/Comfyui.md
      - Domain Transfer: Dev/DomXfer.md
      - General Queries: Dev/General.md
      - Writing Fridays: Dev/WritingFri.md
      - Just Writing: Dev/Writing.md
      - Image Prompts: Dev/Prompts.md

  - Blogs:
      - blogs/index.md
      - Blog Sep25: blogs/Blog2509.md
      - Blog Oct25: blogs/Blog2510.md
      - Blog Nov25: blogs/Blog2511.md
      - Blog Dec25: blogs/Blog2512.md
      - Blog Jan26: blogs/Blog2601.md
      - Blog Feb26: blogs/Blog2602.md

  - Visual Art:
      - visual/index.md
      - 2nd Person: visual/Person2.md
      - AI & Emily: visual/Emilyai.md
      - BBox- SEGS: visual/BBoxSEGS.md
      - ComfyUI 💋: visual/Comfyui.md
      - FluxGym 👭: visual/FluxGym.md
      - GIMP- Tips: visual/GimpTips.md
      - QwenPrompt: visual/QwenPro.md
      - Videos  💧: visual/Videos.md
      - VScripts💛: visual/VScripts.md

  - Music:
      - music/index.md
      - Sketches: music/Sketches.md

  - work:
      - work/index.md
      - Scratch Pad: work/words01.md
      - Apr 13 Prmt: work/words02.md

plugins:
  - search
  - tags
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
